# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190320_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='wight',
            field=models.IntegerField(default=1),
        ),
    ]
