# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permission_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default=1, max_length=52, verbose_name='URL别名'),
            preserve_default=False,
        ),
    ]
