# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_permission_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='Menus',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='menu',
            name='wight',
            field=models.IntegerField(default=1, verbose_name='权重'),
        ),
    ]
