# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20190325_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=108, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=108, verbose_name='权限'),
        ),
    ]
